#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

main() {
  python3 -m pip install -U pip
  python3 -m venv venv
  source venv/bin/activate
  python -m pip install -U pip
  pip install wheel
  pip install mlflow
  pip install mlflow[pipelines]
  pip install mlflow[extras]
  deactivate
}

main "$@"
