#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

tracking_root_directory="./tracking/mlruns"

main() {
  source venv/bin/activate
  mlflow server \
    --backend-store-uri "${tracking_root_directory}" \
    --serve-artifacts \
    --artifacts-destination "${tracking_root_directory}"
  deactivate
}

main "$@"
